services:
  - type: web
    name: transcript-assistant-backend
    env: python
    region: oregon  # Choose a region closest to you
    build:
      os: ubuntu
      python:
        version: 3.10.0
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: true
      - key: PORT
        value: 10000  # Default port if not set by Render
    plan: free

  - type: web
    name: transcript-assistant-frontend
    env: node
    region: oregon  # Match the backend region
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: "./frontend/build"
    envVars:
      - key: NODE_VERSION
        value: 16.x
      - key: REACT_APP_API_URL
        sync: false  # Will be set manually in Render dashboard
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    plan: free
