services:
  - type: web
    name: transcript-assistant
    env: python
    build:
      os: ubuntu
      python:
        version: 3.10.0
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: true
    plan: free

  - type: web
    name: transcript-assistant-frontend
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: "./frontend/build"
    envVars:
      - key: NODE_VERSION
        value: 16.x
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    plan: free
